# Generated by Django 3.2.11 on 2022-01-11 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocuments',
            options={'verbose_name': 'User Document', 'verbose_name_plural': 'User Documents'},
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdocuments',
            unique_together={('user', 'name'), ('user', 'path')},
        ),
    ]
