# Generated by Django 3.2.11 on 2022-01-11 19:58

from django.conf import settings
from django.db import migrations, models
import file_storage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_storage', '0002_auto_20220111_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='file',
            field=models.FileField(default=None, upload_to=file_storage.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userdocuments',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='path',
        ),
    ]
